# Generated by Django 2.2.14 on 2020-08-04 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200725_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
