# Generated by Django 2.2.14 on 2020-08-27 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=django.utils.timezone.now, auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='', verbose_name='Image Newsletter')),
                ('subscribe', models.IntegerField(default=0)),
                ('target', models.IntegerField()),
                ('frequency', models.CharField(choices=[('Dy', 'DAILY'), ('Wy', 'WEEKLY'), ('My', 'MONTHLY')], max_length=2)),
            ],
        ),
    ]
