# Generated by Django 2.2.14 on 2020-07-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('newslettersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletters',
            new_name='Newsletter',
        ),
    ]
