# Generated by Django 2.2.14 on 2020-07-28 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newslettersapp', '0002_auto_20200728_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewslettersUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.ManyToManyField(related_name='newsletter_user', to='newslettersapp.Newsletter')),
                ('user', models.ManyToManyField(related_name='user_newsletter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
