# Generated by Django 2.2.14 on 2020-08-07 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslettersapp', '0002_auto_20200807_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_newsletter', to=settings.AUTH_USER_MODEL),
        ),
    ]
