# Generated by Django 2.2.14 on 2020-08-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newslettersapp', '0003_auto_20200827_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='subscribe',
            new_name='subscribed',
        ),
    ]
