# Generated by Django 2.2.14 on 2020-08-08 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newslettersapp', '0003_auto_20200807_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='user_newsletter_subscribed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='vote',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='vote',
            field=models.ManyToManyField(blank=True, related_name='user_newsletter_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
