# Generated by Django 2.2.14 on 2020-08-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslettersapp', '0004_auto_20200808_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('Dy', 'DAILY'), ('Wy', 'WEEKLY'), ('My', 'MONTHLY')], max_length=2),
        ),
    ]
