# Generated by Django 2.2.14 on 2020-08-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslettersapp', '0005_auto_20200808_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribe',
            field=models.IntegerField(default=0),
        ),
    ]
