# Generated by Django 2.2.14 on 2020-08-12 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newslettersapp', '0006_auto_20200808_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(auto_created=django.utils.timezone.now, null=True),
        ),
    ]
