# Generated by Django 2.2.14 on 2020-08-21 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newslettersapp', '0008_auto_20200819_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(auto_created=django.utils.timezone.now, auto_now_add=True),
        ),
    ]
